# AWS Config
# Both the bucket and dynamodb table are currently running on eu-central-1 
# and contain latest Open Food Facts Data.
region_name: "eu-central-1"
table_name: "open-food-facts"   # DynamoDB table name
bucket_name: "open-food-facts"  # S3 bucket name

# Latest model weights
model_url: "https://tfhub.dev/tensorflow/resnet_50/feature_vector/1?tf-hub-format=compressed"
input_width: 224
input_height: 224
input_channels: 3

# Vector Search Config
embedding_size: 2048 # size of the embedding vectors (num of features) which is calculated by the TFX model
metric: "angular"    # type of distance metric which was used when creating the search index
k: 10                # number of best matches to return